include classpath("application.conf")
node-address { host = "*", port = 9324 }
rest-sqs { enabled = true, bind-port = 9324, bind-hostname = "0.0.0.0", sqs-limits = strict }
rest-stats.enabled = false
messages-storage.enabled = true
queues {
  ingestion-jobs {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 10 seconds
    deadLettersQueue { name = "ingestion-dlq", maxReceiveCount = 5 }
  }
  ingestion-dlq { defaultVisibilityTimeout = 60 seconds }
}
