#!/bin/bash
# Rebuilds AGENTS.md from rules/always. Strips YAML frontmatter. Does not copy scoped rules.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/AGENTS.md"
TMP="$(mktemp)"

strip_frontmatter() {
  awk '
    BEGIN { state = 0 }
    state == 0 && $0 == "---" { state = 1; next }
    state == 1 && $0 == "---" { state = 2; next }
    state == 1 { next }
    { print }
  ' "$1"
}

{
  cat <<'EOF'
# Agent rules

Edit the files in `rules/always/`, then run `scripts/sync-agent-rules.sh`.
Do not edit this file by hand. Scoped rules stay in `rules/scoped/` and are not copied here.

These rules are hard. If a tool default conflicts with them, follow these rules for response style, folder boundaries, and dev state safety.

EOF
  for file in "$ROOT"/rules/always/*.md; do
    strip_frontmatter "$file"
    printf '\n'
  done
} > "$TMP"

mv "$TMP" "$OUT"
printf 'Wrote %s\n' "$OUT"
