#!/bin/bash
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
fail=0

ok() { printf 'ok %s\n' "$1"; }
bad() { printf 'FAIL %s\n' "$1"; fail=1; }

for f in hooks/block-dangerous.sh hooks/self-check.sh scripts/sync-agent-rules.sh .githooks/pre-push; do
  if [[ -x "$f" ]]; then ok "exec $f"; else bad "exec $f"; fi
done

if grep -q 'hooksPath = .githooks' .git/config; then ok "hooksPath"; else bad "hooksPath"; fi

if [[ -f .cursor/hooks.json && -f .claude/settings.json && -f .gitignore ]]; then
  ok "hook configs"
else
  bad "hook configs"
fi

if grep -q 'hooks/denied.log' .gitignore; then ok "gitignore log"; else bad "gitignore log"; fi

if [[ -e .cursor/rules/strict.mdc || -e .qoder/rules/strict.md || -e .agents/rules/strict.md ]]; then
  bad "old strict symlink still present"
else
  ok "old strict removed"
fi

python3 - <<'PY'
import os, sys
root = os.getcwd()
pairs = [
    (".cursor/rules/response-style.mdc", "rules/always/response-style.md"),
    (".cursor/rules/repo.mdc", "rules/always/repo.md"),
    (".cursor/rules/safety.mdc", "rules/always/safety.md"),
    (".cursor/rules/api.mdc", "rules/scoped/api.md"),
    (".cursor/rules/backend.mdc", "rules/scoped/backend.md"),
    (".cursor/rules/bench.mdc", "rules/scoped/bench.md"),
    (".qoder/rules/api.md", "rules/scoped/api.md"),
    (".agents/rules/bench.md", "rules/scoped/bench.md"),
    ("CLAUDE.md", "AGENTS.md"),
    ("GEMINI.md", "AGENTS.md"),
]
bad = False
for link, target in pairs:
    real = os.path.realpath(link)
    expect = os.path.realpath(target)
    if real != expect:
        print(f"FAIL link {link} -> {real}")
        bad = True
    else:
        print(f"ok link {link}")
sys.exit(1 if bad else 0)
PY
[[ $? -eq 0 ]] || fail=1

if grep -q 'Do not edit this file by hand' AGENTS.md && grep -q 'Dev state' AGENTS.md && ! grep -q 'alwaysApply:' AGENTS.md; then
  ok "AGENTS.md synced"
else
  bad "AGENTS.md synced"
fi

for f in rules/always/response-style.md rules/always/repo.md rules/always/safety.md rules/scoped/api.md rules/scoped/backend.md rules/scoped/bench.md; do
  [[ -f "$f" ]] && ok "file $f" || bad "file $f"
done

bash hooks/self-check.sh || fail=1

# pre-push: first push of a branch is allowed. Non-ancestor is blocked.
zero="0000000000000000000000000000000000000000"
new_sha="0123456789abcdef0123456789abcdef01234567"
set +e
printf 'refs/heads/new %s refs/heads/new %s\n' "$new_sha" "$zero" | .githooks/pre-push origin url >/dev/null
code=$?
set -e
if [[ "$code" -eq 0 ]]; then ok "pre-push new branch"; else bad "pre-push new branch ($code)"; fi

set +e
printf 'refs/heads/old %s refs/heads/old %s\n' "$zero" "$new_sha" | .githooks/pre-push origin url >/dev/null
code=$?
set -e
if [[ "$code" -ne 0 ]]; then ok "pre-push delete"; else bad "pre-push delete allowed"; fi

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  head_sha="$(git rev-parse HEAD)"
  # Use a sha that is not an ancestor: the empty tree is not an ancestor of HEAD.
  empty="$(git hash-object -t tree /dev/null)"
  set +e
  printf 'refs/heads/main %s refs/heads/main %s\n' "$head_sha" "$empty" | .githooks/pre-push origin url >/dev/null
  code=$?
  set -e
  if [[ "$code" -ne 0 ]]; then ok "pre-push non-ff"; else bad "pre-push non-ff allowed"; fi
else
  ok "pre-push non-ff skipped (no commits)"
fi

if [[ "$fail" -ne 0 ]]; then
  printf 'verify failed\n'
  exit 1
fi
printf 'verify passed\n'
